language: node_js
node_js: 6

before_script:
  - npm prune

script:
  - npm run build

deploy:
  provider: releases
  api_key:
    secure: DG+CiBi1eNXNR9Ss46vcctqUtTLxZwN0WNb7UdDYKGRtCdtLy3NhcqJQx8KvpO0XwbBQUlAv1uxM0RHXDH49uCk41KrNeqPf/IrtRFzAB3T3XicwPPcSvgfBDF/M+TXDuMWnojSxsX4sWaFrJBYhiRFqVhwFqgq67RMh6qzxkVGSjtS1Jed14R+ord6BtqqFwldFGVeReipvH/VsRlljoXWcZSY5kJR0jzPd/ELu+Wyxd8AZBc+Gai8tHNUC9a5CeDsDiMeuk2aBH72RgUl1IhICr4eoW8wvzT1w3t5b4wI9TuF+RPzCVZB7wOCrDK82ueBOin9MmYzbviB1AOftY38r10B6h3yxX7JYTBpUQ2CuHbjyBz5iy+kOP7zz1pYjVcWaIYQF4JULLruC6cZkN12EErIVbsyiZel/Gv4Qj2iVa6SLFdtayhPjalgF+FQvbUVEBS4ShDQ+LAioDs4UZhRV4nrgKgh8IWqea0nRoGXjn6SqGACdNRz9DSScwI5Cnnuxn8jb3Bprbf27ld7DzUj1J3gghgG5cIeth/ccwiPHTH+KIHGqhQiVw+wqPJuS61OnBRud7dvd5o/QkxLnX8uGjmNL3qZXM8lniMKGXpU1eDYc+f8tO/r8o52Wxsl/hvzPLSMOmHzl6HqOB9JFLWXAZDR/MqG/Dsoav80rzvc=
  file: dist/shutter.js
  skip_cleanup: true
  on:
    repo: anatolinicolae/shutter

notifications:
  slack: sqrd:WV9DuVBW8SLzJuNqOt7jc04m
  email: false
